System.Console.WriteLine("b1");
double b1 = Int32.Parse(Console.ReadLine());
System.Console.WriteLine("k1");
double k1 = Int32.Parse(Console.ReadLine());
System.Console.WriteLine("b2");
double b2 = Int32.Parse(Console.ReadLine());
System.Console.WriteLine("k2");
double k2 = Int32.Parse(Console.ReadLine());
double x = (-b2 + b1 ) / (-k1 + k2);
double y = k2 * x + b2 ; 
Console.WriteLine($"прямые пересекутся в точке X : {x} , Y : {y}");